yolo_detector:
  ros__parameters:
    use_sim_time: true
    image_topic: /camera/image_raw
    model_path: /home/dron/.gz/models/yolo12n_people_package/runs/yolo12s_people_e30_b62/weights/best.pt
    model_architecture: yolo
    inference_backend: ultralytics
    target_labels:
      - person
    input_width: 960
    input_height: 960
    confidence_threshold: 0.35
    score_threshold: 0.25
    nms_threshold: 0.45
    processing_max_rate_hz: 5.0
    publish_debug_image: true
    debug_image_max_rate_hz: 2.0
    detection_hold_sec: 0.75
    swap_rb: true
    dino_resize_mode: stretch
    dino_box_format: cxcywh
    dino_logit_activation: sigmoid
    dino_normalize_mean: [0.485, 0.456, 0.406]
    dino_normalize_std: [0.229, 0.224, 0.225]
